project:
  type: website

website:
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Topics"
        contents: topics/*
      - section: "Image processing"
        contents: 
          - topics/d_processing.qmd
          - topics/processing/a_moco.qmd
      
