project:
  type: website

website:
  navbar:
    left:
      - index.qmd
      - topics.qmd

  sidebar:
    - id: blog
      collapse-level: 2
      contents:
        - topics.qmd
        - section: "Topics"
          contents: topics/*

