---
title: "Models in Nuclear Cardiology"
subtitle: "The tale of Gamma photons from the heart"
author:
  - name: Adam Istvan Szucs
    orcid: 0000-0002-7984-4542
    email: szaqaei@inf.elte.hu
    affiliation: 
      - name: Eötvös Loránd University (Hungary)
      - department: Computer Algebra
date: "2024-12-10"
bibliography: preliminaries.bib
engine: jupyter
format:
  html:
    toc: true
execute:
  echo: true
  freeze: auto
  error: true
from: markdown+emoji
---

```{python}
#|  echo: false
import plotly.io as pio
pio.renderers.default = "plotly_mimetype+notebook_connected"
```

## Introduction
Nuclear cardiology use noninvasive technqiues to assess the myocardial metabolism, evaluate the pumping function of the heart as well as visualize the size and location of the metabolic deficiency.

::: {.callout-note}
## Why is it called nuclear?
The imaging is based on capturing the incident radiation from the injected radiopharmaceuticals. The method is labaled "nuclear" because the gamma photons are the result of radiactive decay.
:::

::: {.callout-important}
## Is it dangerous?
They are completely safe and the uptake and radiation exposure during a heart scan is usually around 1.5 mSv, which compared to the yearly background radiation exposure 2.4 mSv, is negligible.
:::


## Single-photon emission computed tomography

During this class, we will focus building models to solve problems in Single-photon emission computed tomography (SPECT).

## Visualization

```{python}
#| title: Abdominal volume render of a Tc99MIBI scan
#| echo : false
import plotly.graph_objects as go
import numpy as np
import nrrd

X, Y, Z = np.mgrid[0:128:128j, 0:128:128j, 0:128:128j]
vol_data, header = nrrd.read('data/class_webpage_data.nrrd')
vol_data = np.transpose(vol_data, (2, 1, 0))

fig = go.Figure(data=go.Volume(
    x=X.flatten(),
    y=Y.flatten(),
    z=Z.flatten(),
    value=np.flip(vol_data.flatten()),
    isomin=0.01,
    isomax=1.0,
    opacity=0.1, # needs to be small to see through all surfaces
    surface_count=17, # needs to be a large number for good volume rendering
    ))
fig.show()
```

## Base materials

The motivation and the archetype of this class is written in [oftankonyv](http://oftankonyv.reak.bme.hu/).