project:
  type: website
  output-dir: ../docs

website:
  navbar:
    left:
    - text: "Home"
      href: index.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/JacksonFurrier/SQAT
          - text: Report a Bug
            href:  https://github.com/JacksonFurrier/SQAT/issues
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Topics"
        contents: topics/*
      - section: "Image processing"
        contents: 
          - topics/4_processing.qmd
          - topics/processing/1_moco.qmd
      
